### ISSUE TITLE
Duplicate paragraph on welcome page

### ISSUE THREAD

**Issue by katelynprovost** [HackGT/hackgt8-website#6]
Samsung 9 - Chrome browser 
I see duplicate paragraphs answering "What is hackgt?" 
I just scrolled down, I didn't click or do anything else.

![Screenshot_20210712-104523_Chrome](https://user-images.githubusercontent.com/57039762/125307802-5d4f9800-e2fe-11eb-8a21-329dda0ed588.jpg)

**Comment by 1ntEgr8** [comment]
Resolved
