### ISSUE TITLE
Duplicated Text

### ISSUE THREAD

**Issue by Drakodin** [HackGT/hackgt8-website#7]
![image](https://user-images.githubusercontent.com/57043533/125334619-33ec3780-e311-11eb-84dd-4c9d65b8d052.png)

Browsers: Chrome, Firefox
Device/OS: Windows Laptop

It's under the "What is HackGT" section on the page.

**Comment by Drakodin** [comment]
Also it might be intentional from the font-family declaration, but I don't have the custom font showing. I only get Times New Roman.

**Comment by 1ntEgr8** [comment]
@Drakodin this is a resolved issue. You can search through the issues before filing :)

For the font, try hard refreshing.
